name: example
description: A example project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  awaitable_button:
    path: ../
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  altive_lints: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
