name: awaitable_button
description: >
  A button that displays an indicator during asynchronous processing and
  allows callbacks to be executed after completion or exception catch.
version: 1.3.0
homepage: https://github.com/altive/flutter_widgets/blob/main/packages/awaitable_button/README.md
repository: https://github.com/altive/flutter_widgets

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
