name: awaitable_button
description: Await-able Button.
version: 0.0.1
homepage: https://github.com/altive/flutte_widgets/packages/awaitable_button

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
