name: awaitable_button
description: Await-able Button.
version: 0.1.0
homepage: https://github.com/altive/flutter_widgets/blob/main/packages/awaitable_button/README.md
repository: https://github.com/altive/flutter_widgets

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
