name: awaitable_button
description: >
  A button that displays an indicator during asynchronous processing and
  allows callbacks to be executed after completion or exception catch.
version: 0.4.1
homepage: https://github.com/altive/flutter_widgets/blob/main/packages/awaitable_button/README.md
repository: https://github.com/altive/flutter_widgets

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
