name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: packages/awaitable_button/example

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build web --web-renderer canvaskit --base-href="/flutter_widgets/"

      - name: Deploy to GithubPages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/awaitable_button/example/build/web
